#cadastrar usuário
POST http://localhost:8081/cad
Content-Type: application/json

{
  "nome": "Felipe Farias", 
  "email": "felipe@sec.com", 
  "senha": "12345678", 
  "dt_nasc": "2006-05-01T00:00:00.000Z", 
  "telefone": "19998952059", 
  "cpf": "12345678906", 
  "ft_perfil": "sem foto",
  "tipo": 1
}

###
POST http://localhost:8081/cad
Content-Type: application/json

{
  "nome": "Hugo Rocha", 
  "email": "hugo@sec.com", 
  "senha": "12345678", 
  "dt_nasc": "2006-05-01T00:00:00.000Z", 
  "telefone": "19998972055", 
  "cpf": "12345678902", 
  "ft_perfil": "sem foto",
  "tipo": 1
}

###
POST http://localhost:8081/cad
Content-Type: application/json

{
  "nome": "Felipe Farias", 
  "email": "felipe@prof.com", 
  "senha": "12345678", 
  "dt_nasc": "2006-05-01T00:00:00.000Z", 
  "telefone": "19998852055", 
  "cpf": "12345688902", 
  "ft_perfil": "sem foto",
  "tipo": 2
}

###
POST http://localhost:8081/cad
Content-Type: application/json

{
  "nome": "Hugo Rocha", 
  "email": "hugo@prof.com", 
  "senha": "12345678", 
  "dt_nasc": "2006-05-01T00:00:00.000Z", 
  "telefone": "19998952055", 
  "cpf": "12345668902", 
  "ft_perfil": "sem foto",
  "tipo": 2
}

###
#logar em uma conta
POST http://localhost:8081/login
Content-Type: application/json

{
    "email": "hugo@sec.com",
    "senha": "12345678"
}

###
#buscar informações
GET  http://localhost:8081/info/eec1b623-f600-4643-96a0-9784383f0f79
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlZWMxYjYyMy1mNjAwLTQ2NDMtOTZhMC05Nzg0MzgzZjBmNzkiLCJpYXQiOjE3NDQ4NTE5NTksImV4cCI6MTc0NDg1NTU1OX0.e5ZM7g5p_xStm8fC03eSkKDNkyAx7dN4cp7DrIWTOLI

###
#listar usuarios
GET http://localhost:8081/listarUsuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlZWMxYjYyMy1mNjAwLTQ2NDMtOTZhMC05Nzg0MzgzZjBmNzkiLCJpYXQiOjE3NDQ4NTE5NTksImV4cCI6MTc0NDg1NTU1OX0.e5ZM7g5p_xStm8fC03eSkKDNkyAx7dN4cp7DrIWTOLI

###
#excluir usuario
DELETE http://localhost:8081/sec/excluirUsuario/9a856466-41e9-4da1-b36c-ed0915f4a2df
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlZWMxYjYyMy1mNjAwLTQ2NDMtOTZhMC05Nzg0MzgzZjBmNzkiLCJpYXQiOjE3NDQ4NTE5NTksImV4cCI6MTc0NDg1NTU1OX0.e5ZM7g5p_xStm8fC03eSkKDNkyAx7dN4cp7DrIWTOLI


###
#cadastrar curso
POST http://localhost:8081/sec/curso
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNDgxNzMwNy1iNDU3LTQ5NTctYjhlZS1jYmFmMzViMDU2YjkiLCJpYXQiOjE3NDQ0MTg5NzAsImV4cCI6MTc0NDQyMjU3MH0.fJvjjO8Y0VS7AxzsboXycF8cUmhX1ZUKFv_l6PD6sK8

{
  "nome": "Informática Para Internet", 
  "periodo": "Noturno",
  "descricao": "Curso de Informática Para Internet",
  "ch_total": "120",
  "freq_min": "75"
}   

###
#cadastrar materia
POST http://localhost:8081/sec/materia/d9c956fc-78ef-48ef-995b-b3c869339fdc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNDgxNzMwNy1iNDU3LTQ5NTctYjhlZS1jYmFmMzViMDU2YjkiLCJpYXQiOjE3NDQ0MTg5NzAsImV4cCI6MTc0NDQyMjU3MH0.fJvjjO8Y0VS7AxzsboXycF8cUmhX1ZUKFv_l6PD6sK8

{
  "nome": "Programação Web",  
  "descricao": "Curso de Programação Web",
  "ch_total": "120",
  "freq_min": "75"
} 
###
// Listar Usuários
GET http://localhost:8081/listarUsuarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNDgxNzMwNy1iNDU3LTQ5NTctYjhlZS1jYmFmMzViMDU2YjkiLCJpYXQiOjE3NDQ0MTg5NzAsImV4cCI6MTc0NDQyMjU3MH0.fJvjjO8Y0VS7AxzsboXycF8cUmhX1ZUKFv_l6PD6sK8


###
#editar usuario
PUT http://localhost:8081/sec/editarUsuario/eec1b623-f600-4643-96a0-9784383f0f79
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlZWMxYjYyMy1mNjAwLTQ2NDMtOTZhMC05Nzg0MzgzZjBmNzkiLCJpYXQiOjE3NDQ4NDkxNjQsImV4cCI6MTc0NDg0OTc2NH0.7_h5PeOTolO-n0MrLLx4PbjWlNL9hAfHcdpllWG3tnk

{
  "nome": "Felipe Farias", 
  "email": "felipe@sec.com", 
  "senha": "12345678", 
  "dt_nasc": "2006-05-01T00:00:00.000Z", 
  "telefone": "19998952059", 
}

###
#Consultar Usuario
GET http://localhost:8081/sec/consultarUsuario/ae8ef361-b0df-4e9e-b137-373d21c818b6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlZWMxYjYyMy1mNjAwLTQ2NDMtOTZhMC05Nzg0MzgzZjBmNzkiLCJpYXQiOjE3NDUzNDY1NTcsImV4cCI6MTc0NTM1MDE1N30.hmolq0VLJmEESQvko80wUe3_hFM_peqq6iBl3zIKbCA




